#!/usr/bin/env python3
"""
scaffold_feature.py

Scaffold a complete feature module with all layers:
- model (entity, DTOs)
- repository (Spring Data)
- service (interface + implementation)
- controller (REST)
- adapter (external services)
- config (Spring configuration)
- exception (custom exceptions)

Usage:
    python scaffold_feature.py <feature_name> [--package com.example]
    python scaffold_feature.py notifications
    python scaffold_feature.py user_management --package com.myapp
"""

import argparse
import os
import sys
from pathlib import Path
from typing import Optional


# Feature template files
FEATURE_TEMPLATES = {
    "Entity.java": """package {package}.{feature}.model;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * JPA Entity for {feature}.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@Entity
@Table(name = "{table_name}")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@EntityListeners(AuditingEntityListener.class)
public class {Feature}Entity {{

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(unique = true, nullable = false)
    private String uuid;

    @Column(nullable = false)
    private String name;

    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;

    @LastModifiedDate
    @Column(nullable = false)
    private LocalDateTime updatedAt;

    @PrePersist
    protected void onCreate() {{
        if (uuid == null) {{
            uuid = UUID.randomUUID().toString();
        }}
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }}

    @PreUpdate
    protected void onUpdate() {{
        updatedAt = LocalDateTime.now();
    }}
}}
""",

    "CreateRequest.java": """package {package}.{feature}.model;

import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * DTO for creating a new {feature}.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Create{Feature}Request {{

    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    private String name;

    // Add additional fields as needed
}}
""",

    "Response.java": """package {package}.{feature}.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * DTO for {feature} response.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class {Feature}Response {{

    private Long id;
    private String uuid;
    private String name;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;

    public static {Feature}Response fromEntity({Feature}Entity entity) {{
        return {Feature}Response.builder()
                .id(entity.getId())
                .uuid(entity.getUuid())
                .name(entity.getName())
                .createdAt(entity.getCreatedAt())
                .updatedAt(entity.getUpdatedAt())
                .build();
    }}
}}
""",

    "Repository.java": """package {package}.{feature}.repository;

import {package}.{feature}.model.{Feature}Entity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

import java.util.Optional;
import java.util.UUID;

/**
 * Spring Data JPA repository for {Feature}Entity.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@Repository
public interface {Feature}Repository extends
        JpaRepository<{Feature}Entity, Long>,
        JpaSpecificationExecutor<{Feature}Entity> {{

    Optional<{Feature}Entity> findByUuid(String uuid);

    boolean existsByUuid(String uuid);
}}
""",

    "Service.java": """package {package}.{feature}.service;

import {package}.{feature}.model.{Feature}Response;
import {package}.{feature}.model.Create{Feature}Request;

import java.util.List;

/**
 * Service interface for {feature} business logic.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
public interface {Feature}Service {{

    {Feature}Response create(Create{Feature}Request request);

    {Feature}Response getByUuid(String uuid);

    List<{Feature}Response> findAll();

    {Feature}Response update(String uuid, Create{Feature}Request request);

    void delete(String uuid);
}}
""",

    "ServiceImpl.java": """package {package}.{feature}.service.impl;

import {package}.{feature}.model.{Feature}Entity;
import {package}.{feature}.model.{Feature}Response;
import {package}.{feature}.model.Create{Feature}Request;
import {package}.{feature}.repository.{Feature}Repository;
import {package}.{feature}.service.{Feature}Service;
import {package}.{feature}.exception.{Feature}Exception;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Service implementation for {feature} business logic.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@Service
@Slf4j
@RequiredArgsConstructor
@Transactional(readOnly = true)
public class {Feature}ServiceImpl implements {Feature}Service {{

    private final {Feature}Repository repository;

    @Override
    @Transactional
    public {Feature}Response create(Create{Feature}Request request) {{
        log.info("Creating {feature}", request.getName());

        // Check if {feature} already exists
        // Add your validation logic here

        {Feature}Entity entity = {Feature}Entity.builder()
                .name(request.getName())
                .build();

        entity = repository.save(entity);
        log.info("Created {feature} with uuid: {{}}", entity.getUuid());

        return {Feature}Response.fromEntity(entity);
    }}

    @Override
    public {Feature}Response getByUuid(String uuid) {{
        log.debug("Fetching {feature} by uuid: {{}}", uuid);

        {Feature}Entity entity = repository.findByUuid(uuid)
                .orElseThrow(() -> new {Feature}Exception(
                        "{Feature} not found with uuid: " + uuid
                ));

        return {Feature}Response.fromEntity(entity);
    }}

    @Override
    public List<{Feature}Response> findAll() {{
        log.debug("Fetching all {feature}s");

        return repository.findAll().stream()
                .map({Feature}Response::fromEntity)
                .collect(Collectors.toList());
    }}

    @Override
    @Transactional
    public {Feature}Response update(String uuid, Create{Feature}Request request) {{
        log.info("Updating {feature} with uuid: {{}}", uuid);

        {Feature}Entity entity = repository.findByUuid(uuid)
                .orElseThrow(() -> new {Feature}Exception(
                        "{Feature} not found with uuid: " + uuid
                ));

        entity.setName(request.getName());
        entity = repository.save(entity);

        log.info("Updated {feature} with uuid: {{}}", entity.getUuid());
        return {Feature}Response.fromEntity(entity);
    }}

    @Override
    @Transactional
    public void delete(String uuid) {{
        log.info("Deleting {feature} with uuid: {{}}", uuid);

        {Feature}Entity entity = repository.findByUuid(uuid)
                .orElseThrow(() -> new {Feature}Exception(
                        "{Feature} not found with uuid: " + uuid
                ));

        repository.delete(entity);
        log.info("Deleted {feature} with uuid: {{}}", uuid);
    }}
}}
""",

    "Controller.java": """package {package}.{feature}.controller;

import {package}.{feature}.model.{Feature}Response;
import {package}.{feature}.model.Create{Feature}Request;
import {package}.{feature}.service.{Feature}Service;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.List;

/**
 * REST controller for {feature} operations.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@RestController
@RequestMapping("/api/v1/{feature_path}")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "{Feature}", description = "{Feature} management endpoints")
public class {Feature}Controller {{

    private final {Feature}Service service;

    @PostMapping
    @Operation(summary = "Create a new {feature}")
    public ResponseEntity<{Feature}Response> create(
            @Valid @RequestBody Create{Feature}Request request) {{
        {Feature}Response response = service.create(request);
        return ResponseEntity.status(HttpStatus.CREATED).body(response);
    }}

    @GetMapping("/{{uuid}}")
    @Operation(summary = "Get {feature} by UUID")
    public ResponseEntity<{Feature}Response> getByUuid(
            @Parameter(description = "{Feature} UUID") @PathVariable String uuid) {{
        {Feature}Response response = service.getByUuid(uuid);
        return ResponseEntity.ok(response);
    }}

    @GetMapping
    @Operation(summary = "Get all {feature}s")
    public ResponseEntity<List<{Feature}Response>> findAll() {{
        List<{Feature}Response> responses = service.findAll();
        return ResponseEntity.ok(responses);
    }}

    @PutMapping("/{{uuid}}")
    @Operation(summary = "Update {feature}")
    public ResponseEntity<{Feature}Response> update(
            @Parameter(description = "{Feature} UUID") @PathVariable String uuid,
            @Valid @RequestBody Create{Feature}Request request) {{
        {Feature}Response response = service.update(uuid, request);
        return ResponseEntity.ok(response);
    }}

    @DeleteMapping("/{{uuid}}")
    @Operation(summary = "Delete {feature}")
    public ResponseEntity<Void> delete(
            @Parameter(description = "{Feature} UUID") @PathVariable String uuid) {{
        service.delete(uuid);
        return ResponseEntity.noContent().build();
    }}
}}
""",

    "Exception.java": """package {package}.{feature}.exception;

/**
 * Custom exception for {feature} operations.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
public class {Feature}Exception extends RuntimeException {{

    public {Feature}Exception(String message) {{
        super(message);
    }}

    public {Feature}Exception(String message, Throwable cause) {{
        super(message, cause);
    }}
}}
""",

    "Config.java": """package {package}.{feature}.config;

import org.springframework.context.annotation.Configuration;

/**
 * Configuration class for {feature}.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@Configuration
public class {Feature}Config {{

    // Add your configuration beans here
    // Example: @Bean for external service clients, etc.
}}
""",

    "Adapter.java": """package {package}.{feature}.adapter;

import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Component;

/**
 * External adapter for {feature} integrations.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@Component
@Slf4j
@RequiredArgsConstructor
public class {Feature}ExternalAdapter {{

    // Add external service calls here
    // Example: REST clients, message producers, etc.

    // public void sendEvent({Feature}Event event) {{
    //     log.debug("Sending {feature} event: {{}}", event);
    //     // Implementation here
    // }}
}}
""",

    "GlobalExceptionHandler.java": """package {package}.{feature}.config;

import {package}.{feature}.exception.{Feature}Exception;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.ExceptionHandler;
import org.springframework.web.bind.annotation.RestControllerAdvice;

import java.time.LocalDateTime;
import java.util.HashMap;
import java.util.Map;

/**
 * Global exception handler for {feature}.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@RestControllerAdvice
@Slf4j
public class {Feature}ExceptionHandler {{

    @ExceptionHandler({Feature}Exception.class)
    public ResponseEntity<Map<String, Object>> handle{Feature}Exception({Feature}Exception ex) {{
        log.error("{Feature} exception: {{}}", ex.getMessage(), ex);

        Map<String, Object> error = new HashMap<>();
        error.put("timestamp", LocalDateTime.now().toString());
        error.put("status", HttpStatus.BAD_REQUEST.value());
        error.put("error", "Bad Request");
        error.put("message", ex.getMessage());

        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body(error);
    }}

    @ExceptionHandler(Exception.class)
    public ResponseEntity<Map<String, Object>> handleGenericException(Exception ex) {{
        log.error("Unexpected error: {{}}", ex.getMessage(), ex);

        Map<String, Object> error = new HashMap<>();
        error.put("timestamp", LocalDateTime.now().toString());
        error.put("status", HttpStatus.INTERNAL_SERVER_ERROR.value());
        error.put("error", "Internal Server Error");
        error.put("message", "An unexpected error occurred");

        return ResponseEntity.status(HttpStatus.INTERNAL_SERVER_ERROR).body(error);
    }}
}}
""",

    "ServiceTest.java": """package {package}.{feature}.service;

import {package}.{feature}.model.{Feature}Entity;
import {package}.{feature}.model.{Feature}Response;
import {package}.{feature}.model.Create{Feature}Request;
import {package}.{feature}.repository.{Feature}Repository;
import {package}.{feature}.service.impl.{Feature}ServiceImpl;
import {package}.{feature}.exception.{Feature}Exception;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.Optional;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

/**
 * Unit tests for {Feature}Service.
 * Generated by scaffold_feature.py - Review and modify as needed.
 */
@ExtendWith(MockitoExtension.class)
class {Feature}ServiceTest {{

    @Mock
    private {Feature}Repository repository;

    @InjectMocks
    private {Feature}ServiceImpl service;

    private {Feature}Entity testEntity;
    private Create{Feature}Request testRequest;

    @BeforeEach
    void setUp() {{
        testEntity = {Feature}Entity.builder()
                .id(1L)
                .uuid("test-uuid")
                .name("Test {Feature}")
                .build();

        testRequest = Create{Feature}Request.builder()
                .name("Test {Feature}")
                .build();
    }}

    @Test
    void create_ShouldSaveAndReturnResponse() {{
        // Given
        when(repository.save(any({Feature}Entity.class))).thenReturn(testEntity);

        // When
        {Feature}Response response = service.create(testRequest);

        // Then
        assertNotNull(response);
        assertEquals("Test {Feature}", response.getName());
        verify(repository, times(1)).save(any({Feature}Entity.class));
    }}

    @Test
    void getByUuid_WhenExists_ShouldReturnResponse() {{
        // Given
        when(repository.findByUuid("test-uuid")).thenReturn(Optional.of(testEntity));

        // When
        {Feature}Response response = service.getByUuid("test-uuid");

        // Then
        assertNotNull(response);
        assertEquals("Test {Feature}", response.getName());
    }}

    @Test
    void getByUuid_WhenNotExists_ShouldThrowException() {{
        // Given
        when(repository.findByUuid("non-existent")).thenReturn(Optional.empty());

        // When & Then
        assertThrows({Feature}Exception.class, () -> service.getByUuid("non-existent"));
    }}
}}
""",
}


class FeatureScaffolder:
    """Scaffolds a complete Java feature module."""

    def __init__(self, feature_name: str, base_package: str = "com.example", base_path: str = "src/main/java"):
        self.feature_name = feature_name.lower().replace("-", "").replace(" ", "")
        self.Feature = self._to_pascal_case(feature_name)
        self.base_package = base_package
        self.base_path = base_path

    def _to_pascal_case(self, name: str) -> str:
        """Convert feature name to PascalCase."""
        parts = name.lower().replace("-", " ").replace("_", " ").split()
        return "".join(word.capitalize() for word in parts)

    def _get_table_name(self) -> str:
        """Get database table name from feature name."""
        return self.feature_name.replace("_", "")

    def _get_feature_path(self) -> str:
        """Get URL path for the feature."""
        return self.feature_name.replace("_", "-")

    def _get_package_path(self) -> str:
        """Get file system path for the package."""
        return self.base_package.replace(".", "/")

    def _format_template(self, template: str) -> str:
        """Format template with feature-specific values."""
        return template.format(
            package=self.base_package,
            feature=self.feature_name,
            Feature=self.Feature,
            table_name=self._get_table_name(),
            feature_path=self._get_feature_path()
        )

    def scaffold(self, output_dir: str = ".") -> bool:
        """Generate the feature structure."""
        # Base directory for Java source
        java_base = Path(output_dir) / self.base_path / self._get_package_path() / self.feature_name

        if java_base.exists():
            print(f"Error: Directory '{java_base}' already exists.")
            return False

        print(f"Scaffolding feature '{self.Feature}' at: {java_base}")

        # Create directory structure
        directories = [
            "model",
            "repository",
            "service/impl",
            "controller",
            "adapter",
            "config",
            "exception"
        ]

        for dir_name in directories:
            dir_path = java_base / dir_name
            dir_path.mkdir(parents=True, exist_ok=True)
            print(f"  Created: {dir_path}")

        # Create files
        files = {
            f"model/{self.Feature}Entity.java": "Entity.java",
            f"model/Create{self.Feature}Request.java": "CreateRequest.java",
            f"model/{self.Feature}Response.java": "Response.java",
            f"repository/{self.Feature}Repository.java": "Repository.java",
            f"service/{self.Feature}Service.java": "Service.java",
            f"service/impl/{self.Feature}ServiceImpl.java": "ServiceImpl.java",
            f"controller/{self.Feature}Controller.java": "Controller.java",
            f"exception/{self.Feature}Exception.java": "Exception.java",
            f"config/{self.Feature}Config.java": "Config.java",
            f"adapter/{self.Feature}ExternalAdapter.java": "Adapter.java",
            f"config/{self.Feature}ExceptionHandler.java": "GlobalExceptionHandler.java",
        }

        for file_path, template_name in files.items():
            full_path = java_base / file_path
            content = self._format_template(FEATURE_TEMPLATES[template_name])

            with open(full_path, 'w', encoding='utf-8') as f:
                f.write(content)

            print(f"  Created: {full_path}")

        # Create test directory structure
        test_base = Path(output_dir) / "src/test/java" / self._get_package_path() / self.feature_name
        test_base.mkdir(parents=True, exist_ok=True)
        print(f"  Created: {test_base}")

        # Create test file
        test_path = test_base / f"service/{self.Feature}ServiceTest.java"
        test_content = self._format_template(FEATURE_TEMPLATES["ServiceTest.java"])

        with open(test_path, 'w', encoding='utf-8') as f:
            f.write(test_content)
        print(f"  Created: {test_path}")

        print(f"\n✅ Feature '{self.Feature}' scaffolded successfully!")
        print(f"\nNext steps:")
        print(f"  1. Review and modify the generated files")
        print(f"  2. Implement your business logic")
        print(f"  3. Add tests")
        print(f"  4. Run validation: python .claude/skills/expert-java-backend-developer/scripts/generate_quality_report.py {java_base}")

        return True


def main():
    parser = argparse.ArgumentParser(
        description="Scaffold a complete Java feature module"
    )
    parser.add_argument("feature_name", help="Name of the feature (e.g., notifications, user_management)")
    parser.add_argument("--package", default="com.example", help="Base package (default: com.example)")
    parser.add_argument("--output", default=".", help="Output directory (default: current directory)")

    args = parser.parse_args()

    scaffolder = FeatureScaffolder(
        feature_name=args.feature_name,
        base_package=args.package
    )

    success = scaffolder.scaffold(output_dir=args.output)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
