#!/usr/bin/env python3
"""
Hierarchical Documentation Generator - Generates L0, L1, L2, L3 documentation levels.
"""

import json
from pathlib import Path
from typing import Dict, List, Optional
from datetime import datetime
import argparse


class HierarchicalDocsGenerator:
    """Generates multi-level documentation for different audiences."""
    
    def __init__(self, output_dir: Path, verbose: bool = False):
        self.output_dir = Path(output_dir)
        self.verbose = verbose
    
    def log(self, msg: str):
        if self.verbose:
            print(f"   [docs] {msg}")
    
    def generate(self, scan_data: Dict) -> List[str]:
        """Generate all documentation levels."""
        generated = []
        
        # L0: Executive Summary
        self._generate_l0(scan_data)
        generated.append("L0_EXECUTIVE_SUMMARY.md")
        
        # L1: Architecture
        self._generate_l1(scan_data)
        generated.append("L1_ARCHITECTURE/")
        
        # L2: Domains
        self._generate_l2(scan_data)
        generated.append("L2_DOMAINS/")
        
        # L3: Modules (only if requested or for specific components)
        if scan_data.get("generate_l3", True):
            self._generate_l3(scan_data)
            generated.append("L3_MODULES/")
        
        # Master Index
        self._generate_index(scan_data)
        generated.append("INDEX.md")
        
        return generated
    
    def _generate_l0(self, scan_data: Dict):
        """Generate L0: Executive Summary (1 page)."""
        project = scan_data.get("project_info", {})
        structure = scan_data.get("structure", {})
        
        content = f"""# 📊 Executive Summary

> **Auto-generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
> **Purpose**: Quick overview for executives, new team members, stakeholders

---

## What is this project?

**{project.get("type", "Software Project")}** built with {", ".join(project.get("languages", ["Unknown"])[:3])}.

## Quick Stats

| Metric | Value |
|--------|-------|
| Total Files | {structure.get("total_files", 0):,} |
| Lines of Code | {structure.get("total_lines", 0):,} |
| Modules | {len(structure.get("modules", []))} |
| Architecture | {project.get("architecture", "N/A")} |

## Tech Stack

"""
        for fw in project.get("frameworks", [])[:5]:
            content += f"- {fw}\n"
        
        content += f"""
## Key Modules

| Module | Purpose | Size |
|--------|---------|------|
"""
        for mod in structure.get("modules", [])[:6]:
            content += f"| **{mod.get('name', 'N/A')}** | {mod.get('type', 'module')} | {mod.get('file_count', 0)} files |\n"
        
        content += f"""
## Next Steps

1. **Architecture details** → Read `L1_ARCHITECTURE/OVERVIEW.md`
2. **Specific domain** → Browse `L2_DOMAINS/<domain>/`
3. **Deep code dive** → Check `L3_MODULES/<module>/`

---

*Generated by Codebase Scanner v2.0*
"""
        
        path = self.output_dir / "L0_EXECUTIVE_SUMMARY.md"
        path.parent.mkdir(parents=True, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        self.log(f"Generated: {path}")
    
    def _generate_l1(self, scan_data: Dict):
        """Generate L1: Architecture level documentation."""
        project = scan_data.get("project_info", {})
        structure = scan_data.get("structure", {})
        
        l1_dir = self.output_dir / "L1_ARCHITECTURE"
        l1_dir.mkdir(parents=True, exist_ok=True)
        
        # OVERVIEW.md
        overview = f"""# Architecture Overview

> **Audience**: Architects, Tech Leads, Senior Developers

## System Architecture

**Pattern**: {project.get("architecture", "Not detected")}

## Layers

"""
        # Detect layers from structure
        dirs = structure.get("by_directory", {})
        layer_names = {"features": "Feature Modules", "apps": "Applications", "lib": "Libraries", 
                       "middleware": "Middleware", "routers": "Routing", "utils": "Utilities",
                       "config": "Configuration", "static": "Static Assets"}
        
        for dir_name, info in dirs.items():
            layer = layer_names.get(dir_name, dir_name.title())
            overview += f"### {layer}\n- **Path**: `{dir_name}/`\n- **Files**: {info.get('file_count', 0)}\n\n"
        
        overview += """
## Key Design Decisions

See `../../.github/memory-bank/DECISIONS.md` for architectural decisions log.

## Dependencies

External dependencies are managed via:
"""
        if project.get("package_manager"):
            overview += f"- **Package Manager**: {project.get('package_manager')}\n"
        
        with open(l1_dir / "OVERVIEW.md", "w", encoding="utf-8") as f:
            f.write(overview)
        
        # TECH_STACK.md
        tech_stack = f"""# Technology Stack

## Languages
"""
        for lang in project.get("languages", []):
            tech_stack += f"- {lang}\n"
        
        tech_stack += "\n## Frameworks & Libraries\n"
        for fw in project.get("frameworks", []):
            tech_stack += f"- {fw}\n"
        
        tech_stack += f"""
## Infrastructure

- **Build System**: {project.get("build_system", "N/A")}
- **CI/CD**: {project.get("ci_cd", "N/A")}
- **Database**: {project.get("database", "N/A")}
- **Test Framework**: {project.get("test_framework", "N/A")}
"""
        
        with open(l1_dir / "TECH_STACK.md", "w", encoding="utf-8") as f:
            f.write(tech_stack)
        
        # DESIGN_PATTERNS.md
        patterns = f"""# Design Patterns

## Detected Patterns

### Architecture Pattern
- **{project.get("architecture", "Unknown").replace("_", " ").title()}**

### Common Patterns Found

Based on code analysis:
"""
        
        # Add patterns based on detected files/structure
        if any("service" in m.get("name", "").lower() for m in structure.get("modules", [])):
            patterns += "- **Service Layer Pattern** - Business logic encapsulated in services\n"
        if any("repository" in m.get("name", "").lower() for m in structure.get("modules", [])):
            patterns += "- **Repository Pattern** - Data access abstraction\n"
        if any("controller" in m.get("name", "").lower() for m in structure.get("modules", [])):
            patterns += "- **Controller Pattern** - Request handling\n"
        
        with open(l1_dir / "DESIGN_PATTERNS.md", "w", encoding="utf-8") as f:
            f.write(patterns)
        
        self.log(f"Generated L1_ARCHITECTURE/")
    
    def _generate_l2(self, scan_data: Dict):
        """Generate L2: Domain level documentation."""
        structure = scan_data.get("structure", {})
        
        l2_dir = self.output_dir / "L2_DOMAINS"
        l2_dir.mkdir(parents=True, exist_ok=True)
        
        # INDEX.md
        index = """# Domain Index

| Domain | Path | Files | Description |
|--------|------|-------|-------------|
"""
        
        for mod in structure.get("modules", []):
            name = mod.get("name", "unknown")
            path = mod.get("path", "")
            files = mod.get("file_count", 0)
            index += f"| [{name}](./{name}/OVERVIEW.md) | `{path}` | {files} | {mod.get('type', 'module')} |\n"
            
            # Create domain folder
            domain_dir = l2_dir / name
            domain_dir.mkdir(parents=True, exist_ok=True)
            
            # Domain OVERVIEW.md
            domain_overview = f"""# {name.title()}

> **Path**: `{path}`
> **Files**: {files}
> **Type**: {mod.get('type', 'module')}

## Overview

This module is part of the {mod.get('type', 'feature')} layer.

## Structure

See detailed structure in `../../L3_MODULES/{name}/` for:
- Interfaces
- Functions
- Dependencies

## Key Files

Check the module for:
- Entry points
- Public APIs
- Configuration

## Related Domains

*(Cross-references to be added based on dependency analysis)*
"""
            with open(domain_dir / "OVERVIEW.md", "w", encoding="utf-8") as f:
                f.write(domain_overview)
        
        with open(l2_dir / "INDEX.md", "w", encoding="utf-8") as f:
            f.write(index)
        
        self.log(f"Generated L2_DOMAINS/")
    
    def _generate_l3(self, scan_data: Dict):
        """Generate L3: Module deep-dive documentation."""
        structure = scan_data.get("structure", {})
        
        l3_dir = self.output_dir / "L3_MODULES"
        l3_dir.mkdir(parents=True, exist_ok=True)
        
        # INDEX.md
        index = """# Module Index

Deep-dive documentation for each module.

| Module | Path | Files |
|--------|------|-------|
"""
        
        for mod in structure.get("modules", []):
            name = mod.get("name", "unknown")
            path = mod.get("path", "")
            files = mod.get("file_count", 0)
            index += f"| [{name}](./{name}/OVERVIEW.md) | `{path}` | {files} |\n"
            
            # Create module folder
            mod_dir = l3_dir / name
            mod_dir.mkdir(parents=True, exist_ok=True)
            
            # Module OVERVIEW.md
            overview = f"""# {name.title()} - Deep Dive

> **Path**: `{path}`
> **Files**: {files}

## File Structure

```
{path}/
├── (file list to be generated)
└── ...
```

## Interfaces

*Public interfaces exported by this module*

## Functions

*Public functions exported by this module*

## Dependencies

### Internal Dependencies
*(Other modules this depends on)*

### External Dependencies
*(Third-party packages used)*

## Usage Examples

```
// Example usage to be added
```
"""
            with open(mod_dir / "OVERVIEW.md", "w", encoding="utf-8") as f:
                f.write(overview)
        
        with open(l3_dir / "INDEX.md", "w", encoding="utf-8") as f:
            f.write(index)
        
        self.log(f"Generated L3_MODULES/")
    
    def _generate_index(self, scan_data: Dict):
        """Generate master index for navigation."""
        project = scan_data.get("project_info", {})
        structure = scan_data.get("structure", {})
        
        content = f"""# 📚 Documentation Index

> **Project**: {project.get("type", "Unknown")}
> **Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

## Quick Navigation

| Level | Audience | Link |
|-------|----------|------|
| L0 | Executives, New Members | [Executive Summary](./L0_EXECUTIVE_SUMMARY.md) |
| L1 | Architects, Tech Leads | [Architecture](./L1_ARCHITECTURE/OVERVIEW.md) |
| L2 | Team Leads, Feature Devs | [Domains](./L2_DOMAINS/INDEX.md) |
| L3 | Developers | [Modules](./L3_MODULES/INDEX.md) |

## Semantic Analysis

| Report | Description |
|--------|-------------|
| [Business Rules](./SEMANTIC/BUSINESS_RULES.md) | Extracted business logic |
| [Security](./SEMANTIC/SECURITY_ANALYSIS.md) | Security findings |
| [Tech Debt](./SEMANTIC/TECH_DEBT.md) | TODOs, FIXMEs, issues |
| [Data Flow](./SEMANTIC/DATA_FLOW.md) | Data transformation paths |
| [Complexity](./SEMANTIC/COMPLEXITY.md) | Code complexity metrics |

## Domains

| Domain | Files |
|--------|-------|
"""
        for mod in structure.get("modules", []):
            content += f"| [{mod.get('name', 'N/A')}](./L2_DOMAINS/{mod.get('name', 'unknown')}/OVERVIEW.md) | {mod.get('file_count', 0)} |\n"
        
        content += """
## How to Use

1. **New to project?** → Start with L0
2. **Understanding architecture?** → Read L1
3. **Working on feature?** → Check L2 for your domain
4. **Deep debugging?** → Dive into L3

---

*Use `/scan-refresh` to update this documentation*
"""
        
        with open(self.output_dir / "INDEX.md", "w", encoding="utf-8") as f:
            f.write(content)
        
        self.log(f"Generated INDEX.md")


def main():
    parser = argparse.ArgumentParser(description="Generate hierarchical documentation")
    parser.add_argument("--input", "-i", required=True, help="Input directory with JSON files")
    parser.add_argument("--output", "-o", required=True, help="Output directory")
    parser.add_argument("--level", type=int, choices=[0, 1, 2, 3], help="Generate only specific level")
    parser.add_argument("--verbose", "-v", action="store_true", help="Verbose output")
    
    args = parser.parse_args()
    
    input_dir = Path(args.input)
    scan_data = {}
    
    for json_file in ["project_info.json", "structure.json", "dependencies.json", "apis.json"]:
        path = input_dir / json_file
        if path.exists():
            with open(path) as f:
                key = json_file.replace(".json", "")
                scan_data[key] = json.load(f)
    
    gen = HierarchicalDocsGenerator(Path(args.output), args.verbose)
    generated = gen.generate(scan_data)
    
    print(f"Generated {len(generated)} documentation items")
    return 0


if __name__ == "__main__":
    exit(main())
