spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/av_platform_dev

logging:
  level:
    com.vnpt.avplatform: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.kafka: DEBUG
