spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/av_platform_dev
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  elasticsearch:
    uris: http://localhost:9200

influxdb:
  url: http://localhost:8086
  token: dev-token
  org: vnpt-av
  bucket: av-platform-analytics-dev

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket: av-platform-reports-dev

logging:
  level:
    com.vnpt.avplatform: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.data.elasticsearch: DEBUG
